movie_analysis/urls.py
from django.contrib import admin
from django.urls import path
from ptt_movie import views as movie_analysis_views

urlpatterns = [
    path('admin/', admin.site.urls),
	path('',movie_analysis_views.index),
	path('b/',movie_analysis_views.analysis),
	path('search/',movie_analysis_views.analysis_type,name = 'search'),
	path('keyword/<str:key>',movie_analysis_views.keyword,name='keyword'),
	path('month/<str:key>',movie_analysis_views.month,name='month'),
	path('week/<str:key>',movie_analysis_views.week,name='week'),
	path('hot/',movie_analysis_views.hot,name='hot'),
	path('rank/',movie_analysis_views.rank,name='rnk'),
]

handler404 = movie_analysis_views.handler404

ptt_movie/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
	author = models.CharField(max_length = 40)
	title = models.CharField(max_length = 80)
	time = models.DateTimeField()
	ip = models.CharField(max_length = 60, null=True)
	content = models.TextField()
	url = models.CharField(max_length = 80, unique=True, primary_key=True)
	push_message_all = models.IntegerField()
	push_message_good = models.IntegerField()
	push_message_bad = models.IntegerField()
	push_message_neutral = models.IntegerField()
	
	class Meta:
		ordering = ('-time',)
	
	def __str__(self):
		return self.title
		
class Keyword_Yahoo(models.Model):
	movie = models.CharField(max_length = 60)
	keyword = models.CharField(max_length = 256,null=True)
	
	def __str__(self):
		return self.movie
		
class Keyword_Like(models.Model):
	movie = models.CharField(max_length = 60)
	keyword = models.CharField(max_length = 256,null=True)
	
	def __str__(self):
		return self.movie
		
class Keyword(models.Model):
	movie = models.CharField(max_length = 60)
	keyword = models.CharField(max_length = 256,null=True)
	not_keyword = models.CharField(max_length = 256,null=True)
	
	def __str__(self):
		return self.movie

class Keyword_Analysis(models.Model):
	name = models.CharField(max_length = 60, primary_key=True)
	article = models.IntegerField()
	discussion = models.IntegerField()
	good = models.IntegerField()
	bad = models.IntegerField()
	score = models.FloatField()
	comment = models.CharField(max_length = 10)
	def __str__(self):
		return self.name

class Keyword_Analysis_This_Week(models.Model):
	name = models.CharField(max_length = 60, primary_key=True)
	article = models.IntegerField()
	discussion = models.IntegerField()
	good = models.IntegerField()
	bad = models.IntegerField()
	score = models.FloatField()
	comment = models.CharField(max_length = 10)
	def __str__(self):
		return self.name

class Keyword_Analysis_Last_Week(models.Model):
	name = models.CharField(max_length = 60, primary_key=True)
	article = models.IntegerField()
	discussion = models.IntegerField()
	good = models.IntegerField()
	bad = models.IntegerField()
	score = models.FloatField()
	comment = models.CharField(max_length = 10)
	def __str__(self):
		return self.name
		
class Keyword_Analysis_This_Month(models.Model):
	name = models.CharField(max_length = 60, primary_key=True)
	article = models.IntegerField()
	discussion = models.IntegerField()
	good = models.IntegerField()
	bad = models.IntegerField()
	score = models.FloatField()
	comment = models.CharField(max_length = 10)
	def __str__(self):
		return self.name

class Keyword_Analysis_Last_Month(models.Model):
	name = models.CharField(max_length = 60, primary_key=True)
	article = models.IntegerField()
	discussion = models.IntegerField()
	good = models.IntegerField()
	bad = models.IntegerField()
	score = models.FloatField()
	comment = models.CharField(max_length = 10)
	def __str__(self):
		return self.name

ptt_movie/forms.py
from django import forms
from ptt_movie.models import Keyword,Keyword_Analysis

class AddForm(forms.Form):
	a = forms.IntegerField()
	b = forms.IntegerField()
	
class MoiveForm(forms.Form):
	movie_keyword_name = forms.CharField(label='電影關鍵字名稱')
	
	
class ItemForm(forms.ModelForm):
	name = forms.ModelChoiceField(Keyword.objects.all(), label='名稱', widget=forms.Select(attrs={'class':'form-control'}))
	comment = forms.CharField(label='評論', widget=forms.Textarea(attrs={'class': 'tinymceTextarea'}))
	article = forms.IntegerField(label='文章數', widget=forms.NumberInput(attrs={'class':'form-control'}))
	discussion = forms.IntegerField(label='討論數', widget=forms.NumberInput(attrs={'class':'form-control'}))
	good = forms.IntegerField(label='好評數', widget=forms.NumberInput(attrs={'class':'form-control'}))
	bad = forms.IntegerField(label='負評數', widget=forms.NumberInput(attrs={'class':'form-control'}))
	score = forms.IntegerField(label='評分', widget=forms.NumberInput(attrs={'class':'form-control'}))
	
	class Meta:
		model = Keyword_Analysis
		fields = ('name', 'article', 'discussion', 'good', 'bad', 'score' , 'comment',)

ptt_movie/views.py
from django.shortcuts import render
from django.http import HttpResponse
from dateutil.relativedelta import relativedelta
from ptt_movie.models import Keyword_Analysis_This_Month, Keyword_Analysis_Last_Month, Keyword_Analysis_Last_Week, Keyword_Analysis_This_Week
import json

# Create your views here.
"""
def index(request):
	return render(request, 'index.html')
	
def add(request):
	a = request.GET['a']
	b = request.GET['b']
	a = int(a)
	b = int(b)
	return HttpResponse(str(a+b))


from .forms import AddForm

def index(request):
	if request.method == 'POST':
		form = AddForm(request.POST)
	
		if form.is_valid():
			a = form.cleaned_data['a']
			b = form.cleaned_data['b']
			return HttpResponse(str(int(a)+int(b)))
	else:
		form = AddForm()
	return render(request,'ptt_movie/index.html',{'form':form})	
"""
from .search_of_article import article_search
from ptt_movie.models import Keyword_Analysis,Keyword
from django.db.models import Sum
from decimal import Decimal
def index(request):
	
	#今日
	today = datetime.datetime.today().date()
	
	#今日討論電影關鍵字
	todays_keywords = set()
	
	#所有關鍵字
	keywords = Keyword.objects.all()
	keyword_len = len(keywords)
	discussion_len = Article.objects.aggregate(Sum('push_message_all'))['push_message_all__sum']
	article_len = Article.objects.count()
	
	#近一週整體討論量
	#Article.objects.filter(time__year=today.strftime('%Y'),time__month=today.strftime('%m'),time__day=today.strftime('%d'))
	start_date = today - relativedelta(days=7)
	label_of_7_days = list()
	for i in range(1,8):
		label_of_7_days.append((start_date + relativedelta(days=i)).strftime('%m-%d'))
	label_of_7_days = json.dumps(label_of_7_days)
	
	discussion_tihs_week_datas = list()
	for i in range(1,8):
		discussion_tihs_week_datas.append(Article.objects.filter(time__year=start_date.strftime('%Y'),time__month=start_date.strftime('%m'),time__day=(start_date+relativedelta(days=i)).strftime('%d')).aggregate(Sum('push_message_all'))['push_message_all__sum'])
	discussion_tihs_week_datas = json.dumps(discussion_tihs_week_datas)
	
	#近一週討論比例(最多六筆)	
	datas = Keyword_Analysis_This_Week.objects.all().order_by("-discussion")[:6]
	
	if(len(datas)>0):
		if(datas[0].discussion>0):
			keyword_analysis_of_this_week = []
			for data in datas:
				temp = {
					"a_movie": data.name,
					"b_article": data.article,
					"c_discussion": data.discussion,
					"d_good": data.good,
					"e_bad": data.bad,
					"f_score": data.score,
					"g_comment": data.comment,
					"i_name": data.name,
				}
				keyword_analysis_of_this_week.append(temp)
			
			keyword_discussion_of_this_week = list()
			keyword_label_of_this_week = list()
			for i in range(len(keyword_analysis_of_this_week)):
				if(i%6==0):
					keyword_analysis_of_this_week[i].update({'h_color':'text-primary'})
				elif(i%6==1):
					keyword_analysis_of_this_week[i].update({'h_color':'text-danger'})
				elif(i%6==2):
					keyword_analysis_of_this_week[i].update({'h_color':'text-info'})
				elif(i%6==3):
					keyword_analysis_of_this_week[i].update({'h_color':'text-warning'})
				elif(i%6==4):
					keyword_analysis_of_this_week[i].update({'h_color':'text-muted'})
				elif(i%6==5):
					keyword_analysis_of_this_week[i].update({'h_color':'text-success'})
				keyword_discussion_of_this_week.append(keyword_analysis_of_this_week[i]['c_discussion'])
				#keyword_label_of_this_week.append(keyword_analysis_of_this_week[i]['a_movie'])
				#print(keyword_analysis_of_this_week[i])
			#print(keyword_discussion_of_this_week)
			
			for i in range(len(keyword_analysis_of_this_week)):
				#label = keyword_analysis_of_this_week[i]['a_movie']
				label = keyword_analysis_of_this_week[i]['i_name'] + ' (' + str( round(keyword_analysis_of_this_week[i]['c_discussion'] / sum(keyword_discussion_of_this_week) *100, 1) ) + '%)'
				keyword_analysis_of_this_week[i].update({'i_name':label})
				keyword_label_of_this_week.append(label)
				
			keyword_discussion_of_this_week = json.dumps(keyword_discussion_of_this_week)
			keyword_label_of_this_week = json.dumps(keyword_label_of_this_week,ensure_ascii=False)
		
		else:
		
			datas = Keyword_Analysis_This_Week.objects.all().order_by("-article")[:6]
			keyword_analysis_of_this_week = []
			for data in datas:
				temp = {
					"a_movie": data.name,
					"b_article": data.article,
					"c_discussion": data.discussion,
					"d_good": data.good,
					"e_bad": data.bad,
					"f_score": data.score,
					"g_comment": data.comment,
				}
				keyword_analysis_of_this_week.append(temp)
			
			keyword_discussion_of_this_week = list()
			keyword_label_of_this_week = list()
			for i in range(len(keyword_analysis_of_this_week)):
				if(i%6==0):
					keyword_analysis_of_this_week[i].update({'h_color':'text-primary'})
				elif(i%6==1):
					keyword_analysis_of_this_week[i].update({'h_color':'text-danger'})
				elif(i%6==2):
					keyword_analysis_of_this_week[i].update({'h_color':'text-info'})
				elif(i%6==3):
					keyword_analysis_of_this_week[i].update({'h_color':'text-warning'})
				elif(i%6==4):
					keyword_analysis_of_this_week[i].update({'h_color':'text-muted'})
				elif(i%6==5):
					keyword_analysis_of_this_week[i].update({'h_color':'text-success'})
				keyword_discussion_of_this_week.append(keyword_analysis_of_this_week[i]['b_article'])
				#keyword_label_of_this_week.append(keyword_analysis_of_this_week[i]['a_movie'])
				#print(keyword_analysis_of_this_week[i])
			#print(keyword_discussion_of_this_week)
			
			for i in range(len(keyword_analysis_of_this_week)):
				#label = keyword_analysis_of_this_week[i]['a_movie']
				label = keyword_analysis_of_this_week[i]['a_movie'] + ' (' + str( round(keyword_analysis_of_this_week[i]['b_article'] / sum(keyword_discussion_of_this_week) *100, 1) ) + '%)'
				keyword_analysis_of_this_week[i].update({'a_movie':label})
				keyword_label_of_this_week.append(label)
				
			keyword_discussion_of_this_week = json.dumps(keyword_discussion_of_this_week)
			keyword_label_of_this_week = json.dumps(keyword_label_of_this_week,ensure_ascii=False)

		
	#今日文章
	article_today = Article.objects.filter(time__year=today.strftime('%Y'),time__month=today.strftime('%m'),time__day=today.strftime('%d'))
	
	"""
	尋找今日電影關鍵字的快速做法
	
	"""
	article_str = ''
	
	for _article_today in article_today:
		article_str += _article_today.title + ' '
	article_str = article_str.strip()
	
	for _keyword in keywords:
		
		if(_keyword.movie in article_str):
			todays_keywords.add(_keyword.movie)
			
		for same_keyword in _keyword.keyword.strip().split(' '):
			if(same_keyword.strip()!='') and (same_keyword.strip() in article_str):
				todays_keywords.add(_keyword.movie)

	#今日熱門關鍵字
	data_of_today_keyword = list()
	if(len(todays_keywords)>0):
		for todays_keyword in todays_keywords:
			data_of_today_keyword.append(article_search(3,todays_keyword,[2019,int(today.strftime('%m')),int(today.strftime('%d'))]))
		data_of_today_keyword.sort(key=lambda k: k['c_discussion'],reverse=True)

		keyword_today_hot = data_of_today_keyword[0]
		keyword_today_hot_all_data = article_search(0,data_of_today_keyword[0]['a_movie'])
		
		start_date = today - relativedelta(days=7)
		label_of_7_days = list()
		for i in range(1,8):
			label_of_7_days.append((start_date + relativedelta(days=i)).strftime('%m-%d'))
		label_of_7_days = json.dumps(label_of_7_days)

		data_of_7_days = []
		for day in range(1,8):
			data_of_7_days.append(article_search(3,keyword_today_hot['a_movie'],[2019,int((start_date + relativedelta(days=day)).strftime('%m')),int((start_date + relativedelta(days=day)).strftime('%d'))]))

		discussion_of_7_days = list()
		for _data in data_of_7_days:
			discussion_of_7_days.append(_data['c_discussion'])
		discussion_of_7_days = json.dumps(discussion_of_7_days)
		
	#昨日
	yesterday = datetime.datetime.today().date() - relativedelta(days=1)
	
	#昨日討論電影關鍵字
	yesterday_keywords = set()
	
	#昨日文章
	article_yesterday = Article.objects.filter(time__year=yesterday.strftime('%Y'),time__month=yesterday.strftime('%m'),time__day=yesterday.strftime('%d'))
	
	"""
	尋找今日電影關鍵字的快速做法
	
	"""
	article_str = ''
	
	for _article_today in article_yesterday:
		article_str += _article_today.title + ' '
	article_str = article_str.strip()
	
	for _keyword in keywords:
		
		if(_keyword.movie in article_str):
			yesterday_keywords.add(_keyword.movie)
			
		for same_keyword in _keyword.keyword.strip().split(' '):
			if(same_keyword.strip()!='') and (same_keyword.strip() in article_str):
				yesterday_keywords.add(_keyword.movie)

	return render(request,'ptt_movie/index.html', locals())
	

from .forms import MoiveForm
from ptt_movie.models import Article,Keyword
from .tendency import make_tendency_score
import datetime,time

def keyword(request,key):
	keyword_result = Keyword.objects.filter(movie = key)
	if len(keyword_result) != 0:
		movie_name = key
		article_for_keyword = set()
				
		#第一階段搜尋: 只比對與電影關鍵字吻合的文章
		articles = Article.objects.filter(title__icontains=movie_name)
		for article in articles:
			temp = (article.title,article.author,article.time,article.url,article.push_message_all,article.push_message_good,article.push_message_bad,article.push_message_neutral)
			article_for_keyword.add(temp)
			
		#第二階段搜尋: 比對與電影關鍵字附屬關鍵字吻合的文章
		movie_keywords = Keyword.objects.get(movie=movie_name)
		if(len(movie_keywords.keyword.strip())>0):
			for movie_keyword in movie_keywords.keyword.split(' '):
				articles = Article.objects.filter(title__icontains=movie_keyword)
				for article in articles:
					temp = (article.title,article.author,article.time,article.url,article.push_message_all,article.push_message_good,article.push_message_bad,article.push_message_neutral)
					article_for_keyword.add(temp)
			
		#第三階段剃除: 除去內容相似的電影關鍵字資料
		similar_keywords = Keyword.objects.filter(movie__icontains=movie_name)
		if(len(similar_keywords)!=0):
			for similar_keyword in similar_keywords:
				if(similar_keyword.movie!=movie_name):
					articles = Article.objects.filter(title__icontains=similar_keyword.movie)
					for article in articles:

ptt_movie/templates/ptt_movie/footer.html
<!-- footer.html -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
			<p class='sidebar-brand-text'>
				電影溫度計
				<small class="">With Database, Crawler, Keyword Search</small>
			</p>
            <span>Copyright &copy; 何名曜 (B10500062) 2019</span>
          </div>
	  <div class="sidebar-brand ">
	  </div>
        </div>
      </footer>

ptt_movie/templates/ptt_movie/navigation.html
<!--navigation.html-->
{% load crispy_forms_tags %}
		<!-- Topbar -->
        <nav class="navbar-default navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>
		  
		  <a id="nav_brand" class="navbar-brand ml-2" style="font-family: 微軟正黑體" href="/">電影溫度計</a>

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">
		  {% if request.user.is_authenticated %}
            <li class="nav-item dropdown no-arrow d-none d-sm-inline-block">
              <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form action="/search/" class="form-inline m-auto w-100 navbar-search" method="post">
					{% csrf_token %}
                  <div class="input-group">
                    <input id="id_movie_keyword_name" name="movie_keyword_name" type="text" class="form-control bg-light border-0 small h-auto" placeholder="Search for Movie Keyword..." aria-label="Search" aria-describedby="basic-addon2" required="required" {{ input_value }}>
                    <div class="input-group-append">
                      <button class="btn btn-primary" type="submit">
                        <i class="fas fa-search fa-sm"></i>
                      </button>
                    </div>
                  </div>
                </form>
              </div>
            </li>
		  {% else %}
		  <li class="nav-item my-auto">
			  <!-- Topbar Search -->
			  <form action="/search/" class="d-none d-md-inline-block form-inline ml-md-3 my-2 my-md-0 mw-100 navbar-search" method="post">
				{% csrf_token %}
				<div class="input-group">
				  <input id="id_movie_keyword_name" name="movie_keyword_name" type="text" class="form-control bg-light border-0 small h-auto" placeholder="Search for Movie Keyword..." aria-label="Search" aria-describedby="basic-addon2" required="required" {{ input_value }}>
				  <div class="input-group-append">
					<button class="btn btn-primary" type="submit">
					  <i class="fas fa-search fa-sm"></i>
					</button>
				  </div>
				</div>
			  </form>
		  </li>
		  {% endif %}

            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <li class="nav-item dropdown no-arrow d-md-none">
              <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form action="/search/" class="form-inline mr-auto w-100 navbar-search" method="post">
					{% csrf_token %}
                  <div class="input-group">
                    <input id="id_movie_keyword_name" name="movie_keyword_name" type="text" class="form-control bg-light border-0 small h-auto" placeholder="Search for Movie Keyword..." aria-label="Search" aria-describedby="basic-addon2" required="required" {{ input_value }}>
                    <div class="input-group-append">
                      <button class="btn btn-primary" type="submit">
                        <i class="fas fa-search fa-sm"></i>
                      </button>
                    </div>
                  </div>
                </form>
              </div>
            </li>

			{% if request.user.is_authenticated %}
            <!-- Nav Item - Alerts -->
            <li class="nav-item dropdown no-arrow mx-1">
              <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bell fa-fw"></i>
                <!-- Counter - Alerts -->
                <span class="badge badge-danger badge-counter">3+</span>
              </a>
              <!-- Dropdown - Alerts -->
              <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
                <h6 class="dropdown-header">
                  Alerts Center
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="mr-3">
                    <div class="icon-circle bg-primary">
                      <i class="fas fa-file-alt text-white"></i>
                    </div>
                  </div>
                  <div>
                    <div class="small text-gray-500">December 12, 2019</div>
                    <span class="font-weight-bold">A new monthly report is ready to download!</span>
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="mr-3">
                    <div class="icon-circle bg-success">
                      <i class="fas fa-donate text-white"></i>
                    </div>
                  </div>
                  <div>
                    <div class="small text-gray-500">December 7, 2019</div>
                    $290.29 has been deposited into your account!
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="mr-3">
                    <div class="icon-circle bg-warning">
                      <i class="fas fa-exclamation-triangle text-white"></i>
                    </div>
                  </div>
                  <div>
                    <div class="small text-gray-500">December 2, 2019</div>
                    Spending Alert: We've noticed unusually high spending for your account.
                  </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
              </div>
            </li>
			
			
            <!-- Nav Item - Messages -->
            <li class="nav-item dropdown no-arrow mx-1">
              <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-envelope fa-fw"></i>
                <!-- Counter - Messages -->
                <span class="badge badge-danger badge-counter">7</span>
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="messagesDropdown">
                <h6 class="dropdown-header">
                  Message Center
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src="https://source.unsplash.com/fn_BT9fwg_E/60x60" alt="">
                    <div class="status-indicator bg-success"></div>
                  </div>
                  <div class="font-weight-bold">
                    <div class="text-truncate">Hi there! I am wondering if you can help me with a problem I've been having.</div>
                    <div class="small text-gray-500">Emily Fowler · 58m</div>
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src="https://source.unsplash.com/AU4VPcFN4LE/60x60" alt="">
                    <div class="status-indicator"></div>
                  </div>
                  <div>
                    <div class="text-truncate">I have the photos that you ordered last month, how would you like them sent to you?</div>
                    <div class="small text-gray-500">Jae Chun · 1d</div>
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src="https://source.unsplash.com/CS2uCrpNzJY/60x60" alt="">
                    <div class="status-indicator bg-warning"></div>
                  </div>
                  <div>
                    <div class="text-truncate">Last month's report looks great, I am very happy with the progress so far, keep up the good work!</div>
                    <div class="small text-gray-500">Morgan Alvarez · 2d</div>
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60" alt="">
                    <div class="status-indicator bg-success"></div>
                  </div>
                  <div>
                    <div class="text-truncate">Am I a good boy? The reason I ask is because someone told me that people say this to all dogs, even if they aren't good...</div>
                    <div class="small text-gray-500">Chicken the Dog · 2w</div>
                  </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
              </div>
            </li>

            <div class="topbar-divider d-none d-sm-block"></div>

			
            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ request.user.username }}</span>
                <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Profile
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                  Settings
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                  Activity Log
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>
			{% else %}		
			{% endif %}
          </ul>
        </nav>
        <!-- End of Topbar -->